apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/davidcurrie/golang-http-oke:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/davidcurrie/golang-http-oke:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: golang-http-oke
        chartPath: charts/golang-http-oke
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/davidcurrie/golang-http-oke'
          image.tag: '{{.DIGEST_HEX}}'
